#!/bin/sh

EXTRACTOR_INTERFACE=${EXTRACTOR_INTERFACE:=eth0}
EXTRACTOR_PORT=${EXTRACTOR_PORT:=9999}
DETECTOR_ADDRESS=${DETECTOR_ADDRESS:=127.0.0.1}

#sleep 3600

/urlextractor/urlextractor -i ${EXTRACTOR_INTERFACE} | /bin/nc -u ${DETECTOR_ADDRESS} ${EXTRACTOR_PORT}
