version: "3"
services:
  pp-detector:
    image: keiichi/pp-detector
    build:
      context: .
      dockerfile: ./build-parts/detector/Dockerfile
    container_name: pp-detector
    depends_on:
      - pp-extractor
      - pp-wsserver
    ports:
      - 9999:9999/udp   # must be same as EXTRACTOR_PORT
    env_file:
      - phish-finder.env
    volumes:
      - ./whitelist.txt:/detector/server/whitelist.txt:ro
    restart: always
    logging:
      driver: "journald"
  pp-webserver:
    image: keiichi/pp-webserver
    build:
      context: .
      dockerfile: ./build-parts/webserver/Dockerfile
    container_name: pp-webserver
    ports:
      - 8000:80
    env_file:
      - phish-finder.env
    depends_on:
      - pp-wsserver
    restart: always
    logging:
      driver: "journald"
  pp-wsserver:
    image: keiichi/pp-wsserver
    build:
      context: .
      dockerfile: ./build-parts/wsserver/Dockerfile
    container_name: pp-wsserver
    ports:
      - 5678:5678       # must be same as WS_PORT
    env_file:
      - phish-finder.env
    restart: always
    logging:
      driver: "journald"
  pp-extractor:
    image: keiichi/pp-extractor
    build:
      context: .
      dockerfile: ./build-parts/extractor/Dockerfile
    container_name: pp-extractor
    network_mode: host
    env_file:
      - phish-finder.env
    restart: always
    logging:
      driver: "journald"
