version: "3"
services:
  pp-detector:
    image: keiichi/pp-detector
    build:
      context: .
      args:
        - WS_PORT=${WS_PORT}
      dockerfile: ./build-parts/detector/Dockerfile
    container_name: pp-detector
    depends_on:
    #  - pp-extractor
      - pp-wsserver
    ports:
      - ${EXTRACTOR_PORT}:${EXTRACTOR_PORT}/udp
    volumes:
      - ./whitelist.txt:/detector/server/whitelist.txt:ro
    restart: always
    logging:
      driver: "journald"
  pp-webserver:
    image: keiichi/pp-webserver
    build:
      context: .
      args:
        - WS_SERVER=${WS_SERVER}
        - WS_PORT=${WS_PORT}
      dockerfile: ./build-parts/webserver/Dockerfile
    container_name: pp-webserver
    ports:
      - 8000:80
    depends_on:
      - pp-wsserver
    restart: always
    logging:
      driver: "journald"
  pp-wsserver:
    image: keiichi/pp-wsserver
    build:
      context: .
      args:
        - WS_PORT=${WS_PORT}
      dockerfile: ./build-parts/wsserver/Dockerfile
    container_name: pp-wsserver
    ports:
      - ${WS_PORT}:${WS_PORT}
    restart: always
    logging:
      driver: "journald"
  pp-extractor:
    image: keiichi/pp-extractor
    build:
      context: .
      args:
        - EXTRACTOR_INTERFACE=${EXTRACTOR_INTERFACE}
        - EXTRACTOR_PORT=${EXTRACTOR_PORT}
        - DETECTOR_ADDRESS=${DETECTOR_ADDRESS}
      dockerfile: ./build-parts/extractor/Dockerfile
    container_name: pp-extractor
    network_mode: host
    restart: always
    logging:
      driver: "journald"
